import type { AppDictionary } from "../types";

export const app: AppDictionary["app"] = {
  name: "OpenPtl",
  boot: {
    starting: "Iniciando OpenPtl...",
    checkingUpdates: "Verificando atualizações...",
    loadingData: "Carregando dados locais...",
  },
  sync: {
    autoRunning: "Sincronização automática em andamento...",
    autoFailed: "Falha na sincronização automática.",
  },
  header: {
    statusConnected: "Conectado",
    statusDisconnected: "Desconectado",
    login: "Fazer login",
    syncNow: "Sincronizar agora",
    sidebarToggle: "Alternar barra lateral",
    windowMinimize: "Minimizar",
    windowMaximize: "Maximizar",
    windowRestore: "Restaurar",
    windowClose: "Fechar",
    loginServerTitle: "Selecionar servidor de login",
    loginServerDescription: "Escolha qual servidor de autenticação deseja usar antes de continuar.",
    loginServerLoading: "Carregando servidores...",
    loginServerEmpty: "Nenhum servidor disponível para login.",
    loginServerRecommended: "Recomendado",
    loginServerOffline: "offline",
    loginServerUnknownMs: "sem ms",
    loginServerAction: "Fazer login",
    loginServerRefresh: "Atualizar lista",
    hello: "Olá",
    guest: "usuário",
    syncing: "Sincronizando...",
    stageUploading: "Enviando arquivos",
    stageDownloading: "Baixando arquivos",
    stageCleaningRemote: "Limpando remoto",
    stageComplete: "Concluído",
  },
};
