import type { AppDictionary } from "../types";

export const home: AppDictionary["home"] = {
  stats: {
    hosts: "Hosts",
    hostsSub: "Perfis salvos no vault.",
    sessions: "Sessões ativas",
    sessionsSub: "Terminais conectados agora.",
    sync: "Sync",
    syncConnected: "Conectado",
    syncDisconnected: "Desconectado",
    vault: "Vault",
    vaultInitialized: "Inicializado",
    vaultPending: "Pendente",
    vaultLocked: "Bloqueado",
    vaultUnlocked: "Desbloqueado",
  },
  hosts: {
    title: "Hosts",
    newHost: "Novo host",
    emptyTitle: "Nenhum host SSH cadastrado",
    emptyDescription: "Crie um host para abrir terminais e iniciar seu workspace.",
    addButton: "Adicionar host SSH",
    clickToOpen: "Clique para abrir terminal SSH.",
    edit: "Editar",
    remove: "Remover",
  },
  sftp: {
    title: "SFTP",
    newSftp: "Novo SFTP",
    emptyTitle: "Nenhum host SFTP cadastrado",
    emptyDescription: "Adicione um perfil SFTP para navegar e mover arquivos remotos.",
    addButton: "Adicionar host SFTP",
    clickToOpen: "Clique para abrir workspace SFTP.",
    edit: "Editar",
    remove: "Remover",
  },
  sessionsCard: {
    title: "Sessões",
    active: "{count} sessão(ões) ativa(s). Abra mais blocos para trabalhar em paralelo.",
    empty: "Nenhuma sessão ativa. Use os cards SSH/SFTP para iniciar um workspace.",
  },
  connections: {
    title: "Conexões",
    subtitle: "Gerencie conexões Ssh, Sftp, Rdp, FTP(S) e Smb em um único painel.",
    searchPlaceholder: "Buscar conexões...",
    filters: "Filtros",
    filterProtocolLabel: "Protocolo",
    filterProtocolAll: "Todos os protocolos",
    filterStatusLabel: "Status",
    filterStatusAll: "Todos os status",
    filterStatusActive: "Ativas",
    filterStatusIdle: "Inativas",
    filterClear: "Limpar filtros",
    statsTotal: "Total",
    statsSsh: "SSH",
    statsSftp: "SFTP",
    statsProtocols: "Protocolos",
    statusActive: "Ativa",
    statusIdle: "-",
    zeroLabel: "Zero conexões",
    newConnection: "Nova conexão",
    createFirst: "Criar primeira conexão",
    emptyTitle: "Nenhuma conexão cadastrada",
    emptyDescription:
      "Adicione uma conexão para abrir terminal SSH, explorar arquivos SFTP, acessar RDP e criar workspaces por protocolo.",
    openSsh: "Abrir SSH",
    openSftp: "Abrir arquivos",
    openRdp: "Abrir RDP",
    accessAction: "Acessar",
    deleteConfirmTitle: "Excluir conexão",
    deleteConfirmMessage: 'Tem certeza que deseja excluir a conexão "{name}"?',
    deleteConfirmAction: "Excluir",
    quickActions: "Ações rápidas",
    cardHint: "Clique no card para abrir o protocolo principal.",
    protocolSsh: "SSH",
    protocolSftp: "SFTP",
    protocolFtp: "FTP",
    protocolFtps: "FTPS",
    protocolSmb: "SMB",
    protocolRdp: "RDP",
    protocolBoth: "SSH + SFTP",
  },
};
