import type { AppDictionary } from "../types";

export const hostDrawer: AppDictionary["hostDrawer"] = {
  titleEdit: "Editar conexão",
  titleNew: "Nova conexão",
  description: "Defina protocolo, identificação e autenticação da conexão.",
  steps: {
    protocol: "Protocolo",
    connection: "Conexão",
    auth: "Autenticação",
  },
  wizard: {
    selectProtocolTitle: "Selecione o protocolo",
    selectProtocolDescription: "Escolha o tipo de conexão que deseja criar.",
    connectionTitle: "Detalhes da conexão",
    connectionDescription: "Configure host, porta e dados básicos.",
    authTitle: "Autenticação",
    authDescription: "Configure como a conexão será autenticada.",
    back: "Voltar",
    next: "Próximo",
    create: "Salvar conexão",
  },
  name: {
    label: "Nome",
    description: "Nome exibido nos cards e abas do workspace.",
    placeholder: "Ex: Produção - API",
  },
  host: {
    label: "Host/IP",
    description: "Endereço DNS ou IP da máquina remota.",
    placeholder: "Ex: 123.123.123.123",
  },
  port: {
    label: "Porta",
    description: "Porta do servidor para o protocolo selecionado.",
    placeholder: "22",
  },
  username: {
    label: "Usuário",
    description: "Usuário usado para autenticar no servidor.",
    placeholder: "root",
  },
  remotePath: {
    label: "Diretório remoto inicial",
    description: "Diretório inicial ao abrir bloco de arquivos.",
    placeholder: "/var/www/app",
  },
  protocols: {
    label: "Protocolos",
    description: "Selecione quais recursos essa conexão poderá abrir no app.",
    placeholder: "Selecione",
    sshAlsoSftpLabel: "Usar SSH também como SFTP",
    sshAlsoSftpDescription: "Ative para abrir terminal SSH e bloco de arquivos SFTP no mesmo perfil.",
    sshDescription: "Abre blocos de terminal remoto no workspace.",
    sftpDescription: "Abre explorador de arquivos remoto e transferências.",
    ftpDescription: "Abre explorador e transferências remotas via FTP.",
    ftpsDescription: "Abre explorador e transferências remotas via FTPS (TLS).",
    smbDescription: "Abre compartilhamentos SMB para navegar e transferir arquivos.",
    rdpDescription: "Abre acesso remoto de desktop (RDP) no workspace.",
  },
  password: {
    label: "Senha",
    description: "Opcional. Usada quando não houver chave privada.",
    placeholder: "Senha (opcional)",
  },
  auth: {
    passwordMethod: "Senha",
    keyMethod: "Chave SSH",
    agentMethod: "SSH Agent",
    agentUnavailableTitle: "SSH Agent indisponível",
    agentUnavailableDescription: "O backend para SSH Agent ainda não está disponível nesta fase.",
  },
  keychainField: {
    label: "Keychain",
    description: "Selecione uma entrada para preencher senha/chaves automaticamente.",
    none: "Sem keychain",
  },
  privateKey: {
    label: "Chave privada",
    description: "Opcional. Cole a chave ou selecione arquivo local (conteúdo salvo no vault).",
    selectFile: "Selecionar arquivo",
    noFile: "Nenhum arquivo selecionado",
    placeholder: "-----BEGIN OPENSSH PRIVATE KEY-----",
  },
  cancel: "Cancelar",
  save: "Salvar",
};
