import type { AppDictionary } from "../types";

export const keychain: AppDictionary["keychain"] = {
  title: "Keychain",
  subtitle: "Chaves SSH e credenciais seguras.",
  addKeychain: "Adicionar Keychain",
  newKey: "Nova chave",
  newItem: "Novo item",
  importKey: "Importar chave",
  edit: "Editar",
  remove: "Remover",
  password: "Senha",
  privateKey: "Chave privada",
  publicKey: "Chave pública",
  passphrase: "Passphrase",
  emptyTitle: "Nenhuma credencial salva",
  emptyDescription: "Adicione entradas tipadas para SSH, SFTP e senhas compartilhadas.",
  addFirst: "Adicionar primeira entrada",
  typePassword: "Senha",
  typeSshKey: "Chave SSH",
  typeSecret: "Segredo",
  fingerprintLabel: "Fingerprint",
  importDialog: {
    title: "Importar chave",
    description: "Adicione uma chave SSH ao keychain usando o backend real.",
    methodManual: "Manual",
    methodFile: "Arquivo",
    methodPaste: "Colar",
    methodGenerate: "Gerar nova",
    nameLabel: "Nome da chave",
    namePlaceholder: "Ex: id_ed25519_prod",
    passphraseLabel: "Passphrase (opcional)",
    passphrasePlaceholder: "********",
    selectFileTitle: "Selecionar chave SSH",
    readFileError: "Falha ao ler arquivo de chave.",
    saveError: "Falha ao salvar chave no keychain.",
    missingKey: "Informe a chave para continuar.",
    missingManualData: "Preencha os dados obrigatórios para salvar o item.",
    selectFileButton: "Selecionar arquivo de chave",
    fileFormats: ".pem, .key, .pub, .ppk",
    fileContentPlaceholder: "Conteúdo da chave selecionada",
    pasteLabel: "Cole a chave SSH",
    pastePlaceholder: "-----BEGIN OPENSSH PRIVATE KEY-----\n...\n-----END OPENSSH PRIVATE KEY-----",
    algorithmLabel: "Algoritmo",
    algorithmEd25519: "ED25519 (Recomendado)",
    algorithmRsa4096: "RSA 4096",
    algorithmRsa2048: "RSA 2048",
    algorithmEcdsa521: "ECDSA 521",
    commentLabel: "Comentário (opcional)",
    commentPlaceholder: "user@hostname",
    generatedFingerprint: "Fingerprint",
    importAction: "Importar",
    generateAction: "Gerar chave",
    generatingAction: "Gerando...",
  },
  drawer: {
    titleEdit: "Editar keychain",
    titleNew: "Nova keychain",
    description: "Armazene senha, chaves SSH e segredos reutilizáveis.",
    typeLabel: "Tipo da entrada",
    namePlaceholder: "Nome",
    passwordPlaceholder: "Senha (opcional)",
    passphrasePlaceholder: "Passphrase (opcional)",
    privateKeyPlaceholder: "Chave privada (opcional)",
    publicKeyPlaceholder: "Chave pública (opcional)",
    descriptionPassword: "Ideal para senha compartilhada (SSH/SFTP).",
    descriptionSshKey: "Foco em chave privada/pública com passphrase opcional.",
    descriptionSecret: "Entrada flexível com qualquer combinação de campos.",
    cancel: "Cancelar",
    save: "Salvar",
  },
};
