import type { AppDictionary } from "../types";

export const keychain: AppDictionary["keychain"] = {
  title: "Keychain",
  newKey: "Nova Chave",
  edit: "Editar",
  remove: "Remover",
  password: "Password",
  privateKey: "Chave Privada",
  publicKey: "Chave Publica",
  passphrase: "Passphrase",
  emptyTitle: "Nenhuma credencial salva",
  emptyDescription: "Adicione entradas tipadas para SSH, SFTP e senhas compartilhadas.",
  addFirst: "Adicionar primeira entrada",
  typePassword: "Password",
  typeSshKey: "SSH Key",
  typeSecret: "Secret",
  drawer: {
    titleEdit: "Editar Keychain",
    titleNew: "Nova Keychain",
    description: "Armazene senha, chaves SSH e segredos reutilizaveis.",
    typeLabel: "Tipo da entrada",
    namePlaceholder: "Nome",
    passwordPlaceholder: "Password (opcional)",
    passphrasePlaceholder: "Passphrase (opcional)",
    privateKeyPlaceholder: "Chave privada (opcional)",
    publicKeyPlaceholder: "Chave publica (opcional)",
    descriptionPassword: "Ideal para senha compartilhada (SSH/SFTP).",
    descriptionSshKey: "Foco em chave privada/publica com passphrase opcional.",
    descriptionSecret: "Entrada flexivel com qualquer combinacao de campos.",
    cancel: "Cancelar",
    save: "Salvar",
  },
};
