import type { AppDictionary } from "../types";

export const settings: AppDictionary["settings"] = {
  save: "Salvar Configurações",
  sections: {
    application: "Aplicação",
    sync: "Sync e Conectividade",
    sftp: "SFTP",
    terminal: "Terminal",
    modifiedFiles: "Arquivos Modificados",
    googleDrive: "Google Drive",
    masterPassword: "Segurança",
  },
  editor: {
    title: "Editor padrão",
    description: "Defina se o arquivo abre no editor interno, VS Code ou no sistema.",
    internal: "Interno (Monaco)",
    vscode: "VS Code",
    system: "Sistema",
  },
  externalCommand: {
    title: "Comando externo",
    description: "Comando custom para abrir editor externo. Use {filename} no comando.",
    placeholder: "ex: kitty -e nvim {filename}",
  },
  inactivityLock: {
    title: "Bloqueio por inatividade",
    description: "Tempo em minutos para bloquear o vault automaticamente.",
  },
  syncAuto: {
    title: "Sync automático",
    description: "Sincroniza periodicamente quando conectado ao Google Drive.",
  },
  syncStartup: {
    title: "Sync no startup",
    description: "Executa pull automaticamente ao desbloquear o vault.",
  },
  syncOnSave: {
    title: "Sync ao salvar configurações",
    description: "Quando configurações mudarem, executa push automaticamente.",
  },
  syncInterval: {
    title: "Intervalo de sync",
    description: "Frequência em minutos da sincronização automática.",
  },
  sftpChunk: {
    title: "Chunk SFTP (KB)",
    description: "Tamanho do bloco usado em leituras/escritas e transferências SFTP.",
  },
  sftpReconnectDelay: {
    title: "Delay de reconnect SFTP",
    description: "Tempo em segundos para tentar novamente em timeout de conexão/listagem inicial.",
  },
  localServer: {
    editTitle: "Editar Local Server",
    newTitle: "Novo Local Server",
    modalDescription: "Configure label, endereço e autor para o servidor local.",
    saveChanges: "Salvar alterações",
    addServer: "Adicionar servidor",
    connectionTitle: "Connection",
    connectionDescription: "Gerenciamento de servidores de autenticação.",
    editAction: "Editar",
    deleteAction: "Excluir",
  },
  autoReconnect: {
    title: "Auto reconnect SSH",
    description: "Tenta reconectar sessões SSH desconectadas automaticamente.",
  },
  reconnectDelay: {
    title: "Delay de reconnect",
    description: "Tempo de espera em segundos antes de tentar reconectar.",
  },
  copyOnSelect: {
    title: "Copy on select",
    description: "Copia automaticamente o texto selecionado no terminal.",
  },
  rightClickPaste: {
    title: "Paste no clique direito",
    description: "Permite colar com botão direito dentro do bloco de terminal.",
  },
  ctrlShiftShortcuts: {
    title: "Atalhos Ctrl+Shift",
    description: "Ativa Ctrl+Shift+C/V para copiar e colar no terminal.",
  },
  debugLogs: {
    title: "Habilitar logs de depuração",
    description: "Registra erros e problemas do frontend e backend em memória local.",
  },
  knownHosts: {
    title: "Known Hosts",
    description: "Caminho do arquivo known_hosts usado pelo ambiente SSH.",
    placeholder: "~/.ssh/known_hosts",
    selectButton: "Selecionar",
    selectDialog: "Selecionar arquivo known_hosts",
  },
  uploadPolicy: {
    title: "Upload de alterações",
    description: "Define como arquivos alterados no editor interno devem ser enviados.",
    auto: "Enviar automaticamente",
    ask: "Perguntar sempre",
    manual: "Somente manual",
    modalTitle: "Upload de arquivos modificados",
    modalDescription: "Como o OpenPtl deve tratar arquivos modificados no workspace remoto?",
  },
  drive: {
    tabAccount: "Conta",
    tabServer: "Servidor",
    connected: "Conectado",
    userLabel: "Usuário",
    lastSync: "Último sync: {date}",
    connecting: "Conectando...",
    reconnect: "Reconectar",
    connect: "Conectar",
    cancel: "Cancelar",
    push: "Push",
    pull: "Pull",
    serverSearch: "Buscar servidor...",
    serverFilterAll: "Todos",
    serverFilterOnline: "Online",
    serverFilterOffline: "Offline",
    serverEmpty: "Nenhum servidor encontrado.",
    serverCount: "{count} servidor(es)",
    serverPrev: "Anterior",
    serverNext: "Próximo",
    official: "Oficial",
    active: "Ativo",
    offline: "offline",
  },
  password: {
    currentPlaceholder: "Senha atual",
    newPlaceholder: "Nova senha",
    confirmPlaceholder: "Confirmar",
    updateButton: "Atualizar Senha",
  },
  security: {
    warningTitle: "Aviso crítico de criptografia",
    warningDescription:
      "A senha mestre controla toda a criptografia local do OpenPtl. Alterar essa senha recriptografa os dados atuais do aplicativo.",
    changePasswordTitle: "Trocar senha mestre",
    changePasswordDescription:
      "Defina uma nova senha forte. A senha atual é obrigatória para confirmar a alteração.",
    deleteAccountTitle: "Deletar conta",
    deleteAccountDescription:
      "Remove permanentemente todos os dados locais do OpenPtl, incluindo conexões, keychain e configurações.",
    deleteAccountAction: "Deletar conta",
    totalConnections: "Conexões: {count}",
    totalKeychain: "Keychain: {count}",
    totalKnownHosts: "Known hosts: {count}",
    deleteModalTitle: "Confirmar exclusão da conta",
    deleteModalDescription:
      "Esta ação é irreversível e removerá os dados conectados ao OpenPtl neste dispositivo.",
    deleteModalWarningTitle: "Todos os dados serão removidos",
    deleteModalWarningDescription:
      "Ao continuar, todas as conexões, keychain, configurações e dados relacionados ao OpenPtl serão apagados.",
    deleteCloudLabel: "Excluir também os dados na cloud",
    deleteCloudDescription:
      "Quando ativo, remove o backup remoto conectado ao Google Drive antes de apagar os dados locais.",
    deleteCloudUnavailable: "Cloud não conectada. Apenas os dados locais serão removidos.",
    confirmPasswordLabel: "Senha mestre atual (obrigatória)",
    confirmPasswordPlaceholder: "Digite sua senha mestre atual",
    confirmPasswordRequired: "Digite a senha mestre atual para confirmar a exclusão.",
    deletingAction: "Deletando conta...",
    deleteConfirmAction: "Confirmar exclusão",
    deleteSuccess: "Conta removida com sucesso.",
  },
  unsaved: {
    title: "Alterações não salvas",
    description: "Deseja salvar as alterações feitas antes de sair das configurações?",
    saveAndLeave: "Salvar e sair",
    discardAndLeave: "Descartar e sair",
    stay: "Continuar editando",
    preview: "Preview das alterações",
    emptyPreview: "Nenhuma alteração detectada.",
  },
};
