import type { AppDictionary } from "../types";

export const vault: AppDictionary["vault"] = {
  intro: {
    title: "Bem-vindo ao OpenPtl",
    description: "Antes de começar, confira como o app organiza conexões e mantém seu vault protegido.",
    pointOne: "Workspaces com SSH, SFTP, FTP/FTPS, SMB e RDP no mesmo lugar.",
    pointTwo: "Dados sensíveis ficam criptografados localmente com sua senha mestre.",
    pointThree: "Sincronização opcional via Google Drive com controle por servidor.",
    continue: "Continuar",
    skip: "Pular introdução",
    back: "Voltar",
    next: "Próximo",
    start: "Começar",
    stepWelcomeTitle: "Bem-vindo ao OpenPtl",
    stepWelcomeDescription:
      "Um painel de terminal que permite usar múltiplos protocolos — SSH, SFTP, FTP, FTPS, SMB e RDP — com foco em organização e confiança.",
    stepWelcomePointOne: "Gerencie todas as suas conexões em um só lugar.",
    stepWelcomePointTwo: "Workspaces com múltiplas janelas lado a lado.",
    stepWelcomePointThree: "Snap automático estilo Windows para organização.",
    stepDriveTitle: "Seus dados, no seu Drive",
    stepDriveDescription:
      "Uma das ideias centrais é permitir que você guarde informações de conexões no seu próprio Google Drive, sem depender de servidores externos para armazenar dados sensíveis.",
    stepDrivePointOne: "Vault salvo como cloud save no Google Drive.",
    stepDrivePointTwo: "Recupere seus dados em qualquer plataforma.",
    stepDrivePointThree: "Sem backend de armazenamento dedicado.",
    stepAuthTitle: "Servidor de Auth Seguro",
    stepAuthDescription:
      "O servidor usado no auth do Google Drive existe para proteger as chaves privadas do projeto e viabilizar a obtenção do access token de forma segura.",
    stepAuthPointOne: "Chaves privadas dos desenvolvedores protegidas.",
    stepAuthPointTwo: "Access token obtido de forma segura.",
    stepAuthPointThree: "Nenhum dado de conexão trafega pelo servidor.",
    stepSecurityTitle: "Criptografia com Senha Mestre",
    stepSecurityDescription:
      "Todo o OpenPtl é criptografado a partir de uma Senha Mestre. Essa senha desbloqueia o Vault e descriptografa suas informações de conexões e acessos.",
    stepSecurityPointOne: "Vault criptografado end-to-end.",
    stepSecurityPointTwo: "Senha mestre nunca é armazenada.",
    stepSecurityPointThree: "Keychain protegido localmente.",
    setupTitle: "Configurar Vault",
    setupDescription: "Defina uma senha mestre para proteger suas conexões ou recupere um vault existente do Google Drive.",
    setupCreateTitle: "Criar senha mestre",
    setupCreateDescription: "Começar do zero com um novo vault criptografado.",
    setupRecoverTitle: "Recuperar com Google Drive",
    setupRecoverDescription: "Restaurar vault de um backup existente na nuvem.",
    setupHint: "A senha mestre é a única forma de acessar seus dados. Ela nunca é armazenada ou transmitida.",
  },
  init: {
    passwordPlaceholder: "Senha mestre",
    confirmPlaceholder: "Confirmar senha",
    submit: "Inicializar",
    mismatch: "A confirmação da senha não confere.",
  },
  unlock: {
    passwordPlaceholder: "Senha mestre",
    submit: "Desbloquear",
    forgotPassword: "Esqueci a senha?",
  },
  forgot: {
    title: "Esqueci a senha",
    description: "Sem a senha mestre não existe recuperação possível.",
    warning: "Não é possível recuperar dados sem a senha mestre.",
    explanation:
      "Todos os dados do OpenPtl são criptografados localmente. Se você perdeu a senha, a única opção é apagar os dados atuais e iniciar uma conta zerada.",
    confirmLabel: "Digite 'DELETAR DADOS' para continuar",
    confirmPlaceholder: 'Digite "DELETAR DADOS"',
    confirmPhrase: "DELETAR DADOS",
    confirmError: 'Digite exatamente "DELETAR DADOS" para continuar.',
    deleting: "Deletando...",
    deleteButton: "Deletar dados",
    deleteSuccess: "Dados locais removidos. Você pode iniciar do zero.",
  },
  recovery: {
    loginButton: "Logar para recuperar login",
    title: "Recuperar Login",
    description: "Selecione o servidor e recupere seus arquivos da nuvem.",
    serverLabel: "Servidor",
    selectServer: "Selecione um servidor para continuar.",
    invalidServer: "Servidor inválido.",
    enterPassword: "Informe a senha mestre.",
    connecting: "Conectando...",
    loginGoogle: "Login Google",
    validating: "Validando...",
    restoreButton: "Restaurar",
    downloading: "Baixando...",
    backupFound: "Backup encontrado. Informe a senha mestre para validar e baixar os arquivos.",
    downloadingInfo: "Baixando arquivos da nuvem...",
    downloadingWait: "Isso pode levar alguns segundos.",
    restoreSuccess: "Backup restaurado com sucesso.",
    limitReached: "Limite de 5 tentativas atingido. Recuperação cancelada.",
    attempts: "Tentativas: {count}/5",
  },
  toasts: {
    initialized: "Vault inicializado.",
    unlocked: "Vault desbloqueado.",
    lockedInactivity: "Aplicação bloqueada por inatividade.",
    syncStartup: "Sincronizando no startup...",
    syncConflicts: "Conflitos de sincronização detectados no startup.",
    conflictsResolved: "Conflitos resolvidos com sucesso.",
  },
};
