import type { AppDictionary } from "../types";

export const workspace: AppDictionary["workspace"] = {
  tabTitle: "Workspace",
  modeFree: "Livre",
  modeGrid: "Grid",
  addBlock: "Novo Bloco",
  newBlockTitle: "Novo Bloco",
  newBlockDescription: "Escolha qual bloco deseja abrir neste workspace.",
  createLocalTitle: "Locais",
  createRemoteTitle: "Conexões Remotas",
  localTerminal: "Terminal Local",
  localSftp: "SFTP Local",
  localEditor: "Editor Local",
  remoteTerminal: "Terminal Remoto",
  remoteFiles: "Arquivos Remotos",
  remoteRdp: "RDP Remoto",
  sourceLabel: "Conexão",
  sourceHelpTerminal: "Escolha uma conexão SSH para abrir o terminal remoto.",
  sourceHelpFiles: "Escolha uma conexão remota para abrir arquivos (SFTP/FTP/FTPS/SMB).",
  sourceHelpRdp: "Escolha uma conexão RDP para abrir o desktop remoto.",
  accessConnection: "Acessar Conexão",
  selectConnectionTitle: "Abrir Conexão",
  selectConnectionDescription: "Selecione uma conexão salva para abrir neste workspace.",
  selectConnectionSearchPlaceholder: "Buscar conexão...",
  selectConnectionEmpty: "Nenhuma conexão encontrada.",
  blockSftp: "Bloco SFTP",
  blockTerminal: "Bloco Terminal",
  allMinimizedHint: "Todos os blocos estão minimizados. Use a barra superior para restaurar.",
  transfer: "transferencia(s)",
  transferFolder: "Transferencia de pastas ainda esta em rollout. Por enquanto mova arquivos.",
  transferSuccess: "Transferido para {destination}",
  closeTitle: "Fechar workspace",
  closeMessage: 'Deseja realmente fechar "{title}"? Isso encerrara as sessoes associadas.',
  closing: "Fechando...",
  closeConfirm: "Fechar Workspace",
  captureDisabledGeneric: "Captura nativa de teclado/mouse indisponível no momento.",
  captureDisabledWayland: "Captura global no Linux ainda não suporta Wayland nesta fase (use X11).",
  captureDisabledPermission: "Permissão de acessibilidade ausente. Autorize o app para captura global.",
  rdp: {
    title: "Desktop Remoto",
    description: "Conecte um perfil RDP e visualize o frame remoto com atualizacao rapida.",
    noProfiles: "Nenhuma conexao com protocolo RDP foi encontrada.",
    selectProfile: "Selecione um perfil RDP para continuar.",
    profileLabel: "Perfil",
    connecting: "Conectando via RDP...",
    ready: "Conectado",
    authRequired: "Autenticacao necessaria",
    error: "Falha na conexao RDP",
    captureNow: "Capturar agora",
    retry: "Tentar novamente",
    lastFrame: "Ultimo frame",
    resolution: "Resolucao",
    autoRefresh: "Atualizacao automatica",
    waitingFrame: "Aguardando primeiro frame remoto...",
    passwordPlaceholder: "Senha RDP",
    applyPassword: "Aplicar senha e reconectar",
  },
};

