import type { AppDictionary } from "../types";

export const home: AppDictionary["home"] = {
  stats: {
    hosts: "Hosts",
    hostsSub: "Profiles saved in vault.",
    sessions: "Active sessions",
    sessionsSub: "Connected terminals right now.",
    sync: "Sync",
    syncConnected: "Connected",
    syncDisconnected: "Disconnected",
    vault: "Vault",
    vaultInitialized: "Initialized",
    vaultPending: "Pending",
    vaultLocked: "Locked",
    vaultUnlocked: "Unlocked",
  },
  hosts: {
    title: "Hosts",
    newHost: "New host",
    emptyTitle: "No SSH hosts registered",
    emptyDescription: "Create a host to open terminals and start your workspace.",
    addButton: "Add SSH host",
    clickToOpen: "Click to open SSH terminal.",
    edit: "Edit",
    remove: "Remove",
  },
  sftp: {
    title: "SFTP",
    newSftp: "New SFTP",
    emptyTitle: "No SFTP hosts registered",
    emptyDescription: "Add an SFTP profile to browse and move remote files.",
    addButton: "Add SFTP host",
    clickToOpen: "Click to open SFTP workspace.",
    edit: "Edit",
    remove: "Remove",
  },
  sessionsCard: {
    title: "Sessions",
    active: "{count} active session(s). Open more blocks to work in parallel.",
    empty: "No active sessions. Use SSH/SFTP cards to start a workspace.",
  },
  connections: {
    title: "Connections",
    subtitle: "Manage Ssh, Sftp, Rdp, FTP(S) and Smb in one panel.",
    searchPlaceholder: "Search connections...",
    filters: "Filters",
    filterProtocolLabel: "Protocol",
    filterProtocolAll: "All protocols",
    filterStatusLabel: "Status",
    filterStatusAll: "All statuses",
    filterStatusActive: "Active",
    filterStatusIdle: "Idle",
    filterClear: "Clear filters",
    statsTotal: "Total",
    statsSsh: "SSH",
    statsSftp: "SFTP",
    statsProtocols: "Protocols",
    statusActive: "Active",
    statusIdle: "-",
    zeroLabel: "Zero connections",
    newConnection: "New connection",
    createFirst: "Create first connection",
    emptyTitle: "No connections registered",
    emptyDescription:
      "Add a connection to open SSH terminals, browse SFTP files, access RDP and start protocol-aware workspaces.",
    openSsh: "Open SSH",
    openSftp: "Open files",
    openRdp: "Open RDP",
    accessAction: "Access",
    deleteConfirmTitle: "Delete connection",
    deleteConfirmMessage: 'Are you sure you want to delete connection "{name}"?',
    deleteConfirmAction: "Delete",
    quickActions: "Quick actions",
    cardHint: "Click the card to open its primary protocol.",
    protocolSsh: "SSH",
    protocolSftp: "SFTP",
    protocolFtp: "FTP",
    protocolFtps: "FTPS",
    protocolSmb: "SMB",
    protocolRdp: "RDP",
    protocolBoth: "SSH + SFTP",
  },
};
