import type { AppDictionary } from "../types";

export const hostDrawer: AppDictionary["hostDrawer"] = {
  titleEdit: "Edit connection",
  titleNew: "New connection",
  description: "Configure protocol, identity and authentication for the connection.",
  steps: {
    protocol: "Protocol",
    connection: "Connection",
    auth: "Authentication",
  },
  wizard: {
    selectProtocolTitle: "Select protocol",
    selectProtocolDescription: "Choose the type of connection you want to create.",
    connectionTitle: "Connection details",
    connectionDescription: "Configure host, port and basic information.",
    authTitle: "Authentication",
    authDescription: "Configure how this connection should authenticate.",
    back: "Back",
    next: "Next",
    create: "Save connection",
  },
  name: {
    label: "Name",
    description: "Name displayed on cards and workspace tabs.",
    placeholder: "e.g.: Production - API",
  },
  host: {
    label: "Host/IP",
    description: "DNS address or IP of the remote machine.",
    placeholder: "e.g.: 123.123.123.123",
  },
  port: {
    label: "Port",
    description: "Server port for the selected protocol.",
    placeholder: "22",
  },
  username: {
    label: "Username",
    description: "Username used to authenticate on the server.",
    placeholder: "root",
  },
  remotePath: {
    label: "Initial remote directory",
    description: "Initial directory when opening a file block.",
    placeholder: "/var/www/app",
  },
  protocols: {
    label: "Protocols",
    description: "Select which features this connection can open in the app.",
    placeholder: "Select",
    sshAlsoSftpLabel: "Use SSH as SFTP too",
    sshAlsoSftpDescription: "Enable this to use the same profile for SSH terminal and SFTP files.",
    sshDescription: "Opens remote terminal blocks in the workspace.",
    sftpDescription: "Opens remote file explorer and transfers.",
    ftpDescription: "Opens plain FTP remote file explorer and transfers.",
    ftpsDescription: "Opens FTP over TLS (FTPS) explorer and transfers.",
    smbDescription: "Opens SMB shares for remote file browsing and transfers.",
    rdpDescription: "Opens remote desktop access (RDP) in the workspace.",
  },
  password: {
    label: "Password",
    description: "Optional. Used when no private key is available.",
    placeholder: "Password (optional)",
  },
  auth: {
    passwordMethod: "Password",
    keyMethod: "SSH Key",
    agentMethod: "SSH Agent",
    agentUnavailableTitle: "SSH Agent unavailable",
    agentUnavailableDescription: "SSH Agent backend support is not available yet in this phase.",
  },
  keychainField: {
    label: "Keychain",
    description: "Select an entry to auto-fill password/keys.",
    none: "No keychain",
  },
  privateKey: {
    label: "Private key",
    description: "Optional. Paste the key or select a local file (content is saved in vault).",
    selectFile: "Select file",
    noFile: "No file selected",
    placeholder: "-----BEGIN OPENSSH PRIVATE KEY-----",
  },
  cancel: "Cancel",
  save: "Save",
};
