import type { AppDictionary } from "../types";

export const keychain: AppDictionary["keychain"] = {
  title: "Keychain",
  subtitle: "SSH keys and secure credentials.",
  addKeychain: "Add Keychain",
  newKey: "New key",
  newItem: "New item",
  importKey: "Import key",
  edit: "Edit",
  remove: "Remove",
  password: "Password",
  privateKey: "Private key",
  publicKey: "Public key",
  passphrase: "Passphrase",
  emptyTitle: "No credentials saved",
  emptyDescription: "Add typed entries for SSH, SFTP and shared passwords.",
  addFirst: "Add first entry",
  typePassword: "Password",
  typeSshKey: "SSH key",
  typeSecret: "Secret",
  fingerprintLabel: "Fingerprint",
  importDialog: {
    title: "Import key",
    description: "Add an SSH key to keychain using the real backend.",
    methodManual: "Manual",
    methodFile: "File",
    methodPaste: "Paste",
    methodGenerate: "Generate new",
    nameLabel: "Key name",
    namePlaceholder: "Ex: id_ed25519_prod",
    passphraseLabel: "Passphrase (optional)",
    passphrasePlaceholder: "********",
    selectFileTitle: "Select SSH key",
    readFileError: "Failed to read key file.",
    saveError: "Failed to save key to keychain.",
    missingKey: "Provide a key to continue.",
    missingManualData: "Fill required fields before saving this item.",
    selectFileButton: "Select key file",
    fileFormats: ".pem, .key, .pub, .ppk",
    fileContentPlaceholder: "Selected key content",
    pasteLabel: "Paste SSH key",
    pastePlaceholder: "-----BEGIN OPENSSH PRIVATE KEY-----\n...\n-----END OPENSSH PRIVATE KEY-----",
    algorithmLabel: "Algorithm",
    algorithmEd25519: "ED25519 (Recommended)",
    algorithmRsa4096: "RSA 4096",
    algorithmRsa2048: "RSA 2048",
    algorithmEcdsa521: "ECDSA 521",
    commentLabel: "Comment (optional)",
    commentPlaceholder: "user@hostname",
    generatedFingerprint: "Fingerprint",
    importAction: "Import",
    generateAction: "Generate key",
    generatingAction: "Generating...",
  },
  drawer: {
    titleEdit: "Edit keychain",
    titleNew: "New keychain",
    description: "Store passwords, SSH keys and reusable secrets.",
    typeLabel: "Entry type",
    namePlaceholder: "Name",
    passwordPlaceholder: "Password (optional)",
    passphrasePlaceholder: "Passphrase (optional)",
    privateKeyPlaceholder: "Private key (optional)",
    publicKeyPlaceholder: "Public key (optional)",
    descriptionPassword: "Best for shared password use-cases (SSH/SFTP).",
    descriptionSshKey: "Focus on private/public key with optional passphrase.",
    descriptionSecret: "Flexible entry with any combination of fields.",
    cancel: "Cancel",
    save: "Save",
  },
};
