import type { AppDictionary } from "../types";

export const keychain: AppDictionary["keychain"] = {
  title: "Keychain",
  newKey: "New Key",
  edit: "Edit",
  remove: "Remove",
  password: "Password",
  privateKey: "Private Key",
  publicKey: "Public Key",
  passphrase: "Passphrase",
  emptyTitle: "No credentials saved",
  emptyDescription: "Add typed entries for SSH, SFTP and shared passwords.",
  addFirst: "Add first entry",
  typePassword: "Password",
  typeSshKey: "SSH Key",
  typeSecret: "Secret",
  drawer: {
    titleEdit: "Edit Keychain",
    titleNew: "New Keychain",
    description: "Store passwords, SSH keys and reusable secrets.",
    typeLabel: "Entry type",
    namePlaceholder: "Name",
    passwordPlaceholder: "Password (optional)",
    passphrasePlaceholder: "Passphrase (optional)",
    privateKeyPlaceholder: "Private key (optional)",
    publicKeyPlaceholder: "Public key (optional)",
    descriptionPassword: "Best for shared password use-cases (SSH/SFTP).",
    descriptionSshKey: "Focus on private/public key with optional passphrase.",
    descriptionSecret: "Flexible entry with any combination of fields.",
    cancel: "Cancel",
    save: "Save",
  },
};
