import type { AppDictionary } from "../types";

export const settings: AppDictionary["settings"] = {
  save: "Save Settings",
  sections: {
    application: "Application",
    sync: "Sync & Connectivity",
    sftp: "SFTP",
    terminal: "Terminal",
    modifiedFiles: "Modified Files",
    googleDrive: "Google Drive",
    masterPassword: "Security",
  },
  editor: {
    title: "Default editor",
    description: "Choose whether files open in the internal editor, VS Code or system default.",
    internal: "Internal (Monaco)",
    vscode: "VS Code",
    system: "System",
  },
  externalCommand: {
    title: "External command",
    description: "Custom command to open external editor. Use {filename} in the command.",
    placeholder: "e.g.: kitty -e nvim {filename}",
  },
  inactivityLock: {
    title: "Inactivity lock",
    description: "Time in minutes to automatically lock the vault.",
  },
  syncAuto: {
    title: "Auto sync",
    description: "Sync periodically when connected to Google Drive.",
  },
  syncStartup: {
    title: "Sync on startup",
    description: "Automatically pull when unlocking the vault.",
  },
  syncOnSave: {
    title: "Sync on settings save",
    description: "When settings change, automatically push.",
  },
  syncInterval: {
    title: "Sync interval",
    description: "Frequency in minutes for automatic sync.",
  },
  sftpChunk: {
    title: "SFTP Chunk (KB)",
    description: "Block size used for SFTP read/write and transfers.",
  },
  sftpReconnectDelay: {
    title: "SFTP reconnect delay",
    description: "Time in seconds to retry on connection/initial listing timeout.",
  },
  localServer: {
    editTitle: "Edit Local Server",
    newTitle: "New Local Server",
    modalDescription: "Configure label, address and author for the local server.",
    saveChanges: "Save changes",
    addServer: "Add server",
    connectionTitle: "Connection",
    connectionDescription: "Manage authentication servers.",
    editAction: "Edit",
    deleteAction: "Delete",
  },
  autoReconnect: {
    title: "Auto reconnect SSH",
    description: "Try to reconnect disconnected SSH sessions automatically.",
  },
  reconnectDelay: {
    title: "Reconnect delay",
    description: "Wait time in seconds before trying to reconnect.",
  },
  copyOnSelect: {
    title: "Copy on select",
    description: "Automatically copy selected text in the terminal.",
  },
  rightClickPaste: {
    title: "Right-click paste",
    description: "Allow pasting with right-click inside the terminal block.",
  },
  ctrlShiftShortcuts: {
    title: "Ctrl+Shift shortcuts",
    description: "Enable Ctrl+Shift+C/V to copy and paste in the terminal.",
  },
  debugLogs: {
    title: "Enable debug logs",
    description: "Record frontend and backend errors/issues in local in-memory logs.",
  },
  knownHosts: {
    title: "Known Hosts",
    description: "Path to the known_hosts file used by the SSH environment.",
    placeholder: "~/.ssh/known_hosts",
    selectButton: "Select",
    selectDialog: "Select known_hosts file",
  },
  uploadPolicy: {
    title: "Upload changes",
    description: "Define how modified files in the internal editor should be sent.",
    auto: "Send automatically",
    ask: "Always ask",
    manual: "Manual only",
    modalTitle: "Modified file upload",
    modalDescription: "How should OpenPtl handle modified files in the remote workspace?",
  },
  drive: {
    tabAccount: "Account",
    tabServer: "Server",
    connected: "Connected",
    userLabel: "User",
    lastSync: "Last sync: {date}",
    connecting: "Connecting...",
    reconnect: "Reconnect",
    connect: "Connect",
    cancel: "Cancel",
    push: "Push",
    pull: "Pull",
    serverSearch: "Search server...",
    serverFilterAll: "All",
    serverFilterOnline: "Online",
    serverFilterOffline: "Offline",
    serverEmpty: "No servers found.",
    serverCount: "{count} server(s)",
    serverPrev: "Previous",
    serverNext: "Next",
    official: "Official",
    active: "Active",
    offline: "offline",
  },
  password: {
    currentPlaceholder: "Current password",
    newPlaceholder: "New password",
    confirmPlaceholder: "Confirm",
    updateButton: "Update Password",
  },
  security: {
    warningTitle: "Critical encryption warning",
    warningDescription:
      "The master password controls all local OpenPtl encryption. Changing it re-encrypts your current app data.",
    changePasswordTitle: "Change master password",
    changePasswordDescription:
      "Set a strong new password. Your current password is required to confirm this change.",
    deleteAccountTitle: "Delete account",
    deleteAccountDescription:
      "Permanently removes all local OpenPtl data, including connections, keychain entries, and settings.",
    deleteAccountAction: "Delete account",
    totalConnections: "Connections: {count}",
    totalKeychain: "Keychain: {count}",
    totalKnownHosts: "Known hosts: {count}",
    deleteModalTitle: "Confirm account deletion",
    deleteModalDescription:
      "This action is irreversible and will remove connected OpenPtl data on this device.",
    deleteModalWarningTitle: "All data will be removed",
    deleteModalWarningDescription:
      "Continuing will delete all connections, keychain entries, settings, and other OpenPtl-related data.",
    deleteCloudLabel: "Also delete cloud data",
    deleteCloudDescription:
      "When enabled, the connected Google Drive backup is removed before deleting local data.",
    deleteCloudUnavailable: "Cloud not connected. Only local data will be removed.",
    confirmPasswordLabel: "Current master password (required)",
    confirmPasswordPlaceholder: "Enter your current master password",
    confirmPasswordRequired: "Enter the current master password to confirm account deletion.",
    deletingAction: "Deleting account...",
    deleteConfirmAction: "Confirm deletion",
    deleteSuccess: "Account deleted successfully.",
  },
  unsaved: {
    title: "Unsaved changes",
    description: "Do you want to save your changes before leaving settings?",
    saveAndLeave: "Save and leave",
    discardAndLeave: "Discard and leave",
    stay: "Keep editing",
    preview: "Changes preview",
    emptyPreview: "No changes detected.",
  },
};
