import type { AppDictionary } from "../types";

export const vault: AppDictionary["vault"] = {
  intro: {
    title: "Welcome to OpenPtl",
    description: "Before you start, here is how the app handles connections and protects your vault.",
    pointOne: "Workspaces with SSH, SFTP, FTP/FTPS, SMB and RDP in one place.",
    pointTwo: "Sensitive data is encrypted locally using your master password.",
    pointThree: "Optional Google Drive sync with explicit server selection.",
    continue: "Continue",
    skip: "Skip introduction",
    back: "Back",
    next: "Next",
    start: "Start",
    stepWelcomeTitle: "Welcome to OpenPtl",
    stepWelcomeDescription:
      "A terminal control panel that lets you use multiple protocols — SSH, SFTP, FTP, FTPS, SMB and RDP — focused on organization and trust.",
    stepWelcomePointOne: "Manage all your connections in one place.",
    stepWelcomePointTwo: "Workspaces with multiple side-by-side windows.",
    stepWelcomePointThree: "Automatic Windows-style snap for organization.",
    stepDriveTitle: "Your data, in your Drive",
    stepDriveDescription:
      "One core idea is allowing you to store connection data in your own Google Drive, without depending on external servers for sensitive storage.",
    stepDrivePointOne: "Vault saved as cloud save in Google Drive.",
    stepDrivePointTwo: "Recover your data on any platform.",
    stepDrivePointThree: "No dedicated storage backend.",
    stepAuthTitle: "Secure Auth Server",
    stepAuthDescription:
      "The server used for Google Drive auth exists to protect project private keys and enable secure access token retrieval.",
    stepAuthPointOne: "Developers' private keys are protected.",
    stepAuthPointTwo: "Access token is retrieved securely.",
    stepAuthPointThree: "No connection data passes through the server.",
    stepSecurityTitle: "Master Password Encryption",
    stepSecurityDescription:
      "All OpenPtl data is encrypted from your Master Password. This password unlocks the Vault and decrypts your connection and access information.",
    stepSecurityPointOne: "End-to-end encrypted vault.",
    stepSecurityPointTwo: "Master password is never stored.",
    stepSecurityPointThree: "Locally protected keychain.",
    setupTitle: "Set Up Vault",
    setupDescription: "Define a master password to protect your connections or recover an existing vault from Google Drive.",
    setupCreateTitle: "Create master password",
    setupCreateDescription: "Start from scratch with a new encrypted vault.",
    setupRecoverTitle: "Recover with Google Drive",
    setupRecoverDescription: "Restore vault from an existing cloud backup.",
    setupHint: "The master password is the only way to access your data. It is never stored or transmitted.",
  },
  init: {
    passwordPlaceholder: "Master password",
    confirmPlaceholder: "Confirm password",
    submit: "Initialize",
    mismatch: "Password confirmation does not match.",
  },
  unlock: {
    passwordPlaceholder: "Master password",
    submit: "Unlock",
    forgotPassword: "Forgot password?",
  },
  forgot: {
    title: "Forgot password",
    description: "Without the master password, recovery is not possible.",
    warning: "Data cannot be recovered without the master password.",
    explanation:
      "All OpenPtl data is encrypted locally. If you lost your password, the only option is to delete current data and start fresh.",
    confirmLabel: "Type 'DELETE DATA' to continue",
    confirmPlaceholder: 'Type "DELETE DATA"',
    confirmPhrase: "DELETE DATA",
    confirmError: 'Type exactly "DELETE DATA" to continue.',
    deleting: "Deleting...",
    deleteButton: "Delete data",
    deleteSuccess: "Local data removed. You can start fresh.",
  },
  recovery: {
    loginButton: "Login to recover",
    title: "Recover Login",
    description: "Select the server and recover your files from the cloud.",
    serverLabel: "Server",
    selectServer: "Select a server to continue.",
    invalidServer: "Invalid server.",
    enterPassword: "Enter the master password.",
    connecting: "Connecting...",
    loginGoogle: "Google Login",
    validating: "Validating...",
    restoreButton: "Restore",
    downloading: "Downloading...",
    backupFound: "Backup found. Enter the master password to validate and download files.",
    downloadingInfo: "Downloading files from cloud...",
    downloadingWait: "This may take a few seconds.",
    restoreSuccess: "Backup restored successfully.",
    limitReached: "5 attempts limit reached. Recovery cancelled.",
    attempts: "Attempts: {count}/5",
  },
  toasts: {
    initialized: "Vault initialized.",
    unlocked: "Vault unlocked.",
    lockedInactivity: "Application locked due to inactivity.",
    syncStartup: "Syncing on startup...",
    syncConflicts: "Sync conflicts detected on startup.",
    conflictsResolved: "Conflicts resolved successfully.",
  },
};
