import type { AppDictionary } from "../types";

export const workspace: AppDictionary["workspace"] = {
  modeFree: "Free",
  modeGrid: "Grid",
  addBlock: "New Block",
  newBlockTitle: "New Block",
  newBlockDescription: "Choose which block to open in this workspace.",
  blockSftp: "SFTP Block",
  blockTerminal: "Terminal Block",
  transfer: "transfer(s)",
  transferFolder: "Folder transfer is still in rollout. Move files for now.",
  transferSuccess: "Transferred to {destination}",
  closeTitle: "Close workspace",
  closeMessage: 'Do you really want to close "{title}"? This will end associated sessions.',
  closing: "Closing...",
  closeConfirm: "Close Workspace",
  rdp: {
    title: "Remote Desktop",
    description: "Connect an RDP profile and render the remote frame with fast updates.",
    noProfiles: "No connection with RDP protocol was found.",
    selectProfile: "Select an RDP profile to continue.",
    profileLabel: "Profile",
    connecting: "Connecting through RDP...",
    ready: "Connected",
    authRequired: "Authentication required",
    error: "RDP connection failed",
    captureNow: "Capture now",
    retry: "Retry",
    lastFrame: "Last frame",
    resolution: "Resolution",
    autoRefresh: "Auto refresh",
    waitingFrame: "Waiting for first remote frame...",
    passwordPlaceholder: "RDP password",
    applyPassword: "Apply password and reconnect",
  },
};
