export interface AppDictionary {
  app: {
    name: string;
    boot: {
      starting: string;
      checkingUpdates: string;
      loadingData: string;
    };
    sync: {
      autoRunning: string;
      autoFailed: string;
    };
    header: {
      statusConnected: string;
      statusDisconnected: string;
      login: string;
      syncNow: string;
      sidebarToggle: string;
      windowMinimize: string;
      windowMaximize: string;
      windowRestore: string;
      windowClose: string;
      loginServerTitle: string;
      loginServerDescription: string;
      loginServerLoading: string;
      loginServerEmpty: string;
      loginServerRecommended: string;
      loginServerOffline: string;
      loginServerUnknownMs: string;
      loginServerAction: string;
      loginServerRefresh: string;
      hello: string;
      guest: string;
      syncing: string;
      stageUploading: string;
      stageDownloading: string;
      stageCleaningRemote: string;
      stageComplete: string;
    };
  };
  sidebar: {
    home: string;
    keychain: string;
    knownHosts: string;
    settings: string;
    debugLogs: string;
    about: string;
    newConnection: string;
    groupMain: string;
    groupSystem: string;
  };
  vault: {
    intro: {
      title: string;
      description: string;
      pointOne: string;
      pointTwo: string;
      pointThree: string;
      continue: string;
      skip: string;
      back: string;
      next: string;
      start: string;
      stepWelcomeTitle: string;
      stepWelcomeDescription: string;
      stepWelcomePointOne: string;
      stepWelcomePointTwo: string;
      stepWelcomePointThree: string;
      stepDriveTitle: string;
      stepDriveDescription: string;
      stepDrivePointOne: string;
      stepDrivePointTwo: string;
      stepDrivePointThree: string;
      stepAuthTitle: string;
      stepAuthDescription: string;
      stepAuthPointOne: string;
      stepAuthPointTwo: string;
      stepAuthPointThree: string;
      stepSecurityTitle: string;
      stepSecurityDescription: string;
      stepSecurityPointOne: string;
      stepSecurityPointTwo: string;
      stepSecurityPointThree: string;
      setupTitle: string;
      setupDescription: string;
      setupCreateTitle: string;
      setupCreateDescription: string;
      setupRecoverTitle: string;
      setupRecoverDescription: string;
      setupHint: string;
    };
    init: {
      passwordPlaceholder: string;
      confirmPlaceholder: string;
      submit: string;
      mismatch: string;
    };
    unlock: {
      passwordPlaceholder: string;
      submit: string;
      forgotPassword: string;
    };
    forgot: {
      title: string;
      description: string;
      warning: string;
      explanation: string;
      confirmLabel: string;
      confirmPlaceholder: string;
      confirmPhrase: string;
      confirmError: string;
      deleting: string;
      deleteButton: string;
      deleteSuccess: string;
    };
    recovery: {
      loginButton: string;
      title: string;
      description: string;
      serverLabel: string;
      selectServer: string;
      invalidServer: string;
      enterPassword: string;
      connecting: string;
      loginGoogle: string;
      validating: string;
      restoreButton: string;
      downloading: string;
      backupFound: string;
      downloadingInfo: string;
      downloadingWait: string;
      restoreSuccess: string;
      limitReached: string;
      attempts: string;
    };
    toasts: {
      initialized: string;
      unlocked: string;
      lockedInactivity: string;
      syncStartup: string;
      syncConflicts: string;
      conflictsResolved: string;
    };
  };
  home: {
    stats: {
      hosts: string;
      hostsSub: string;
      sessions: string;
      sessionsSub: string;
      sync: string;
      syncConnected: string;
      syncDisconnected: string;
      vault: string;
      vaultInitialized: string;
      vaultPending: string;
      vaultLocked: string;
      vaultUnlocked: string;
    };
    hosts: {
      title: string;
      newHost: string;
      emptyTitle: string;
      emptyDescription: string;
      addButton: string;
      clickToOpen: string;
      edit: string;
      remove: string;
    };
    sftp: {
      title: string;
      newSftp: string;
      emptyTitle: string;
      emptyDescription: string;
      addButton: string;
      clickToOpen: string;
      edit: string;
      remove: string;
    };
    sessionsCard: {
      title: string;
      active: string;
      empty: string;
    };
    connections: {
      title: string;
      subtitle: string;
      searchPlaceholder: string;
      filters: string;
      filterProtocolLabel: string;
      filterProtocolAll: string;
      filterStatusLabel: string;
      filterStatusAll: string;
      filterStatusActive: string;
      filterStatusIdle: string;
      filterClear: string;
      statsTotal: string;
      statsSsh: string;
      statsSftp: string;
      statsProtocols: string;
      statusActive: string;
      statusIdle: string;
      zeroLabel: string;
      newConnection: string;
      createFirst: string;
      emptyTitle: string;
      emptyDescription: string;
      openSsh: string;
      openSftp: string;
      openRdp: string;
      accessAction: string;
      deleteConfirmTitle: string;
      deleteConfirmMessage: string;
      deleteConfirmAction: string;
      quickActions: string;
      cardHint: string;
      protocolSsh: string;
      protocolSftp: string;
      protocolFtp: string;
      protocolFtps: string;
      protocolSmb: string;
      protocolRdp: string;
      protocolBoth: string;
    };
  };
  settings: {
    save: string;
    sections: {
      application: string;
      sync: string;
      sftp: string;
      terminal: string;
      modifiedFiles: string;
      googleDrive: string;
      masterPassword: string;
    };
    editor: {
      title: string;
      description: string;
      internal: string;
      vscode: string;
      system: string;
    };
    externalCommand: {
      title: string;
      description: string;
      placeholder: string;
    };
    inactivityLock: {
      title: string;
      description: string;
    };
    syncAuto: {
      title: string;
      description: string;
    };
    syncStartup: {
      title: string;
      description: string;
    };
    syncOnSave: {
      title: string;
      description: string;
    };
    syncInterval: {
      title: string;
      description: string;
    };
    sftpChunk: {
      title: string;
      description: string;
    };
    sftpReconnectDelay: {
      title: string;
      description: string;
    };
    localServer: {
      editTitle: string;
      newTitle: string;
      modalDescription: string;
      saveChanges: string;
      addServer: string;
      connectionTitle: string;
      connectionDescription: string;
      editAction: string;
      deleteAction: string;
    };
    autoReconnect: {
      title: string;
      description: string;
    };
    reconnectDelay: {
      title: string;
      description: string;
    };
    copyOnSelect: {
      title: string;
      description: string;
    };
    rightClickPaste: {
      title: string;
      description: string;
    };
    ctrlShiftShortcuts: {
      title: string;
      description: string;
    };
    debugLogs: {
      title: string;
      description: string;
    };
    knownHosts: {
      title: string;
      description: string;
      placeholder: string;
      selectButton: string;
      selectDialog: string;
    };
    uploadPolicy: {
      title: string;
      description: string;
      auto: string;
      ask: string;
      manual: string;
      modalTitle: string;
      modalDescription: string;
    };
    drive: {
      tabAccount: string;
      tabServer: string;
      connected: string;
      userLabel: string;
      lastSync: string;
      connecting: string;
      reconnect: string;
      connect: string;
      cancel: string;
      push: string;
      pull: string;
      serverSearch: string;
      serverFilterAll: string;
      serverFilterOnline: string;
      serverFilterOffline: string;
      serverEmpty: string;
      serverCount: string;
      serverPrev: string;
      serverNext: string;
      official: string;
      active: string;
      offline: string;
    };
    password: {
      currentPlaceholder: string;
      newPlaceholder: string;
      confirmPlaceholder: string;
      updateButton: string;
    };
    security: {
      warningTitle: string;
      warningDescription: string;
      changePasswordTitle: string;
      changePasswordDescription: string;
      deleteAccountTitle: string;
      deleteAccountDescription: string;
      deleteAccountAction: string;
      totalConnections: string;
      totalKeychain: string;
      totalKnownHosts: string;
      deleteModalTitle: string;
      deleteModalDescription: string;
      deleteModalWarningTitle: string;
      deleteModalWarningDescription: string;
      deleteCloudLabel: string;
      deleteCloudDescription: string;
      deleteCloudUnavailable: string;
      confirmPasswordLabel: string;
      confirmPasswordPlaceholder: string;
      confirmPasswordRequired: string;
      deletingAction: string;
      deleteConfirmAction: string;
      deleteSuccess: string;
    };
    unsaved: {
      title: string;
      description: string;
      saveAndLeave: string;
      discardAndLeave: string;
      stay: string;
      preview: string;
      emptyPreview: string;
    };
  };
  keychain: {
    title: string;
    subtitle: string;
    newKey: string;
    newItem: string;
    importKey: string;
    edit: string;
    remove: string;
    password: string;
    privateKey: string;
    publicKey: string;
    passphrase: string;
    emptyTitle: string;
    emptyDescription: string;
    addFirst: string;
    typePassword: string;
    typeSshKey: string;
    typeSecret: string;
    fingerprintLabel: string;
    importDialog: {
      title: string;
      description: string;
      methodManual: string;
      methodFile: string;
      methodPaste: string;
      methodGenerate: string;
      nameLabel: string;
      namePlaceholder: string;
      passphraseLabel: string;
      passphrasePlaceholder: string;
      selectFileTitle: string;
      readFileError: string;
      saveError: string;
      missingKey: string;
      missingManualData: string;
      selectFileButton: string;
      fileFormats: string;
      fileContentPlaceholder: string;
      pasteLabel: string;
      pastePlaceholder: string;
      algorithmLabel: string;
      algorithmEd25519: string;
      algorithmRsa4096: string;
      algorithmRsa2048: string;
      algorithmEcdsa521: string;
      commentLabel: string;
      commentPlaceholder: string;
      generatedFingerprint: string;
      importAction: string;
      generateAction: string;
      generatingAction: string;
    };
    drawer: {
      titleEdit: string;
      titleNew: string;
      description: string;
      typeLabel: string;
      namePlaceholder: string;
      passwordPlaceholder: string;
      passphrasePlaceholder: string;
      privateKeyPlaceholder: string;
      publicKeyPlaceholder: string;
      descriptionPassword: string;
      descriptionSshKey: string;
      descriptionSecret: string;
      cancel: string;
      save: string;
    };
  };
  knownHosts: {
    title: string;
    subtitle: string;
    description: string;
    refresh: string;
    createFile: string;
    pathLabel: string;
    pathDefault: string;
    headerHost: string;
    headerAlgorithm: string;
    headerFingerprint: string;
    headerStatus: string;
    headerType: string;
    headerActions: string;
    removeTooltip: string;
    empty: string;
  };
  about: {
    title: string;
    description: string;
    protocolsLabel: string;
    frameworkLabel: string;
    licenseLabel: string;
    githubButton: string;
    docsButton: string;
    projectSection: string;
    projectVisionSection: string;
    projectVisionP1: string;
    projectVisionP2: string;
    projectVisionP3: string;
    repoLabel: string;
    versionLabel: string;
    updatesInfo: string;
    stackSection: string;
    newPackagesSection: string;
    newPackagesDescription: string;
    licensesSection: string;
    licensesDescription: string;
  };
  debugLogs: {
    title: string;
    description: string;
    followTail: string;
    refresh: string;
    clear: string;
    empty: string;
    disabledTitle: string;
    disabledDescription: string;
  };
  hostDrawer: {
    titleEdit: string;
    titleNew: string;
    description: string;
    steps: { protocol: string; connection: string; auth: string };
    wizard: {
      selectProtocolTitle: string;
      selectProtocolDescription: string;
      connectionTitle: string;
      connectionDescription: string;
      authTitle: string;
      authDescription: string;
      back: string;
      next: string;
      create: string;
    };
    name: { label: string; description: string; placeholder: string };
    host: { label: string; description: string; placeholder: string };
    port: { label: string; description: string; placeholder: string };
    username: { label: string; description: string; placeholder: string };
    remotePath: { label: string; description: string; placeholder: string };
    protocols: {
      label: string;
      description: string;
      placeholder: string;
      sshAlsoSftpLabel: string;
      sshAlsoSftpDescription: string;
      sshDescription: string;
      sftpDescription: string;
      ftpDescription: string;
      ftpsDescription: string;
      smbDescription: string;
      rdpDescription: string;
    };
    password: { label: string; description: string; placeholder: string };
    auth: {
      passwordMethod: string;
      keyMethod: string;
      agentMethod: string;
      agentUnavailableTitle: string;
      agentUnavailableDescription: string;
    };
    keychainField: { label: string; description: string; none: string };
    privateKey: {
      label: string;
      description: string;
      selectFile: string;
      noFile: string;
      placeholder: string;
    };
    cancel: string;
    save: string;
  };
  workspace: {
    tabTitle: string;
    modeFree: string;
    modeGrid: string;
    addBlock: string;
    newBlockTitle: string;
    newBlockDescription: string;
    createLocalTitle: string;
    createRemoteTitle: string;
    localTerminal: string;
    localSftp: string;
    localEditor: string;
    remoteTerminal: string;
    remoteFiles: string;
    remoteRdp: string;
    sourceLabel: string;
    sourceHelpTerminal: string;
    sourceHelpFiles: string;
    sourceHelpRdp: string;
    accessConnection: string;
    selectConnectionTitle: string;
    selectConnectionDescription: string;
    selectConnectionSearchPlaceholder: string;
    selectConnectionEmpty: string;
    blockSftp: string;
    blockTerminal: string;
    allMinimizedHint: string;
    transfer: string;
    transferFolder: string;
    transferSuccess: string;
    closeTitle: string;
    closeMessage: string;
    closing: string;
    closeConfirm: string;
    captureDisabledGeneric: string;
    captureDisabledWayland: string;
    captureDisabledPermission: string;
    rdp: {
      title: string;
      description: string;
      noProfiles: string;
      selectProfile: string;
      profileLabel: string;
      connecting: string;
      ready: string;
      authRequired: string;
      error: string;
      captureNow: string;
      retry: string;
      lastFrame: string;
      resolution: string;
      autoRefresh: string;
      waitingFrame: string;
      passwordPlaceholder: string;
      applyPassword: string;
    };
  };
  editor: {
    save: string;
    openExternal: string;
    imageError: string;
    videoError: string;
    binaryNoPreview: string;
    binarySize: string;
  };
  conflicts: {
    title: string;
    description: string;
    applying: string;
    applyButton: string;
    keepClient: string;
    keepServer: string;
    local: string;
    server: string;
    absent: string;
  };
  toasts: {
    connectionSaved: string;
    connectionRemoved: string;
    keychainSaved: string;
    keychainRemoved: string;
    settingsSaved: string;
    enterNewPassword: string;
    passwordMismatch: string;
    passwordUpdated: string;
    sessionDisconnected: string;
    sessionReconnecting: string;
    sessionReconnected: string;
    unknownHostConfirm: string;
    connectionCancelledHost: string;
    passwordPrompt: string;
    connectionCancelledPassword: string;
    savePasswordConfirm: string;
    connectionFailed: string;
    selectSourceFile: string;
    fileCopied: string;
    textOnlyEditor: string;
    fileSaved: string;
    mediaCantExport: string;
    fileTooLarge: string;
    knownHostRemoved: string;
  };
  common: {
    cancel: string;
    save: string;
    edit: string;
    remove: string;
    close: string;
    select: string;
    loading: string;
  };
}
